version: '3'

services:
  vgf_nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
#    volumes:
#    - ./grav-admin:/opt/appserver/deploy/grav-admin
    ports:
    - 8080:80
#    - 8433:443
